ejercicio1_4: ejercicio1_4.cpp Rectangulo.o
	g++ ejercicio1_4.cpp Rectangulo.o Coordenada.o -o ejercicio1_4
Rectangulo.o: Rectangulo.cpp Coordenada.o Rectangulo.h
	g++ Rectangulo.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c